baseurl: '/'
permalink: pretty
title: 'Legal Crypto'

logo:
  mobile: "images/logo/sergi-andres-logo.svg"
  mobile_height: "64px"
  mobile_width: "64px"
  desktop: "images/logo/sergi-andres-logo.svg"
  desktop_height: "128px"
  desktop_width: "240px"

collections:
  services:
    output: true
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  indentWidth: 4
  style: compressed # possible values: nested expanded compact compressed
  precision: 10

url:
  - "https://legal-crypto.github.io"
plugins:
  - jekyll-environment-variables
  - jekyll-sitemap


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
